"""add planned_month to song_requests

Revision ID: 1e30ce49bacf
Revises: 0006_notification_entry_link
Create Date: 2026-05-25 01:07:40.175360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e30ce49bacf'
down_revision: Union[str, Sequence[str], None] = '0006_notification_entry_link'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle_members', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('live_events', 'entry_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('song_live_applications', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('song_part_entries', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('song_recruiting_parts', 'required_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('song_requests', sa.Column('planned_month', sa.String(), nullable=True))
    op.alter_column('song_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_live_event_status', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_live_event_status', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'want_invites'::character varying"),
               existing_nullable=False)
    op.alter_column('song_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'recruiting'::character varying"),
               existing_nullable=False)
    op.drop_column('song_requests', 'planned_month')
    op.alter_column('song_recruiting_parts', 'required_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('song_part_entries', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('song_live_applications', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'applied'::character varying"),
               existing_nullable=False)
    op.alter_column('live_events', 'entry_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('circle_members', 'role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'member'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
