"""add bio and favorite_artists to users

Revision ID: 899e726475ee
Revises: 1e30ce49bacf
Create Date: 2026-05-25 23:46:20.490449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899e726475ee'
down_revision: Union[str, Sequence[str], None] = '1e30ce49bacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('favorite_artists', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_artists')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
